### PR TITLE
Adding hiera support. #7713

### PR DESCRIPTION
**Pull request by cropalato**
moving from master branch

### CODE REVIEW

**Comment by nickchappell** [comment]
Just wanted to give you a heads up that I'll be traveling with family for a little while and may not able to review/merge this until after Christmas.

**Comment by nickchappell** [comment]
Hi @cropalato,

Could you rebase and squash against the current develop branch? This page details the steps for what I'm referring to (so I can keep the commit history of the repo cleaner): https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

**Comment by cropalato** [comment]
Hi @nickchappell ,

Rebased.

**Comment by nickchappell** [comment]
Hi @cropalato,

This still has the commits from other PRs in it. Could you squash them and do a force push?

**Comment by cropalato** [comment]
Closing to send a new pr

**Pull request closed without merging**
