### PR TITLE
adding defined type to create a checkcommand object from a source file

### PR DESCRIPTION
**Pull request by smbambling**
Defined type that references a source file for its content as these objects can widely vary between each other.

### CODE REVIEW

**Comment by smbambling** [comment]
Moved from using a source file to a templates.

**Comment by nickchappell** [comment]
Hi @smbambling,

Do you have an ERB template and parameters for the various options in a check command object that you could add?

**Comment by smbambling** [comment]
I currently don't have a template or parameters for a skeleton CheckCommand object.  These can very so much that I'm finding it hard to develop a standard template with parameters.

As in PR #27 I'd make the argument for using templates in place of sourcing a static file with the file server.

**Comment by nickchappell** [comment]
I'm hoping to tackle notify command objects sometime in the next few days, as I think they will have similar sorts of problems. My thoughts on that object type were to use hashes in the Puppet code and then iterators in the ERB template to grab the keys/values from the hashes. Iterating over nested hashes in ERB should be doable. If I can make that work, would you want to refactor this PR modeled after that? If I can make it work the way I have in mind, refactoring this to function in the same way shouldn't be too difficult.

**Comment by smbambling** [comment]
Sure if you wouldn't mind shooting me an example of what your thinking I'll be glad to refactor this request.

**Comment by cropalato** [comment]
i didn't see your pr. I just add a new one PR (29) to fix the same issue.

**Comment by smbambling** [comment]
Your request does seem to follow more of the modules conventions and it nicely done.

I do feel like it's a lot more code and complex then managing a flat file ( served by the file server ) or just managing a template per check command then having all the code in manifest. 

That said this is Nicks module so I'll go with what he decides :)

**Comment by nickchappell** [comment]
I should be able to squeeze in some time to look at #29 and #30 this weekend. @smbambling, after I merge them, would you want to open a PR for each one for adding the ability to specify your own custom template or static file like you did with #27?

At some point in the near future, I may add the ability to do the same thing to the other object types.

**Comment by smbambling** [comment]
Sure I can work on adding that functionality to the object.

After you test a merge in #29 and #30 can you close out this PR ?

**Comment by smbambling** [comment]
Close in favor of request #35

**Pull request closed without merging**
