### PR TITLE
Hotfix objects apply service

### PR DESCRIPTION
**Pull request by moritzfriedrich**
fixed call apply_service_to_host -> apply_service

Perhaps the hiera nameing needs to be adjust.

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Thanks for your input, but the PR looks broken, the final diff is rather short.

Is the final diff the only thing you wanted to change?

**Comment by moritzfriedrich** [comment]
Oh yes, the finall diff is the only changed part. The other stuff was already pushed by someone else.

**Comment by lazyfrosch** [comment]
Ah, good to know.

**Comment by lazyfrosch** [comment]
Though we should also use `icinga2::object::apply_service` in hiera... I'll deprecate the old variable.

**Pull request closed without merging**
