### PR TITLE
Add custom_prepend and custom_append parameter to object/host.pp and

### PR DESCRIPTION
**Pull request by buzzdeee**
the accompanying template. Idea taken from the apply_service
class/template.

This allows me to get around the limitation I faced with regard to apply_service
and the disks, see my comment here:
https://dev.icinga.org/issues/10804

### CODE REVIEW

**Comment by arioch** [comment]
Looking good so far...
Could you also add a spec test to cover this? And maybe a little documentation to README.md as well?

**Comment by buzzdeee** [comment]
good to know it looks good, ;) will look into spec tests/documentation as soon as possible

**Comment by buzzdeee** [comment]
alright, how about this then

**Comment by buzzdeee** [comment]
just rebased onto latest develop

**Comment by buzzdeee** [comment]
ping
rebased for your convenience...

**Comment by arioch** [comment]
Looking good. 👍 
Merged upstream.

**Pull request closed without merging**
