### PR TITLE
Fix quoting of PostgreSQL password in exec

### PR DESCRIPTION
**Pull request by jshholland**
This is a little tricky since single quotes cannot be escaped within a single quoted string, but I have now found a solution.

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi @jshholland,

Were you having issues with the way the password is currently quoted?

**Comment by jshholland** [comment]
I was, with a (randomly generated) password starting with !% that the shell was trying to perform history expansion on. As far as I can tell this PR fixes it.

**Comment by nickchappell** [comment]
Made a [dev.icinga.org](https://dev.icinga.org) for reference: [7675](https://dev.icinga.org/issues/7675)

**Comment by nickchappell** [comment]
Merged. Thanks @jshholland!

**Pull request closed without merging**
