### PR TITLE
Add Apiuser

### PR DESCRIPTION
**Pull request by Reamer**
With Icinga2.4 we have a new object "ApiUser"
https://dev.icinga.org/issues/9471

We should also implement this object.

If anything is missing , please let me know

Greetings Reamer

### CODE REVIEW

**Comment by lazyfrosch** [comment]
lgtm, will merge it later

**Comment by Reamer** [comment]
wait a moment, i will add documentation

**Comment by Reamer** [comment]
Add documentation

**Comment by lazyfrosch** [comment]
Merged, thanks for your work!

**Pull request merged**
