### PR TITLE
Fixing order of the hashes in erb template files

### PR DESCRIPTION
**Pull request by alexxxxx**

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi,

Thanks for the PR. Just wanted to give you a heads up that I'll be traveling with family for a little while and may not able to review/merge this until after Christmas.

**Comment by nickchappell** [comment]
Created a [dev.icinga.org](https://dev.icinga.org) issues: [#8154](https://dev.icinga.org/issues/8154)

**Comment by nickchappell** [comment]
Hi @alexxxxx,

Could you rebase and squash this against the current develop branch?

**Comment by alexxxxx** [comment]
Should be done.
(This is my first PR rebase, I may be wrong)

**Comment by lazyfrosch** [comment]
Hi @alexxxxx,
thanks for your input, but please open a new PR against our develop branch, you can only choose this when creating a PR.

https://help.github.com/articles/using-pull-requests/#changing-the-branch-range-and-destination-repository

Thanks

**Comment by alexxxxx** [comment]
Done,
new PR = #76
Cheers,

**Pull request closed without merging**
