### PR TITLE
Removing double quotes.

### PR DESCRIPTION
**Pull request by cropalato**
I faced problems sometime ago because of some of the double quotes. As it is usually optional, this should be a user decision not something forced. I sent the first version of some of those files and at the beginning was a good idea. Now I'm not 100% sure.

### CODE REVIEW

**Comment by arioch** [comment]
Some of the tests seem to explicitly expect double quotes.
Could you adjust those and rebase it into this PR?

**Comment by cropalato** [comment]
@arioch 
Are you talk about travis?

**Comment by lazyfrosch** [comment]
This is invalid config, names and strings have to be quoted... Unless they are config names and variables.

I've added a function lately to properly output any value, and used that for the vars/env/arguments data, see  icinga2_config_value.

This PR does not make any sense, unless someone would provide all the quoting within their parameters, which also does not make sense.

**Comment by arioch** [comment]
Closing in favor of @lazyfrosch's function.

**Pull request closed without merging**
