### PR TITLE
updating validation of interval to allow resending of alerts to be disab...

### PR DESCRIPTION
**Pull request by smbambling**
Updating the $interval validation to allow for setting more detailed intervals and also allowing you to disable resending of alert notifications.

### CODE REVIEW

**Comment by nickchappell** [comment]
Created a [dev.icinga.org](https://dev.icinga.org) issue: [#8153](https://dev.icinga.org/issues/8153)

**Comment by nickchappell** [comment]
Hi @smbambling,

Could you rebase this against the current develop branch?

**Comment by smbambling** [comment]
Ok rebased off the develop branch

**Comment by nickchappell** [comment]
I merged this into the develop branch. Thanks @smbambling!

**Pull request closed without merging**
