### PR TITLE
Update more object define types to be consistent.

### PR DESCRIPTION
**Pull request by Ziaunys**
- This is a follow up to a PR I made a couple weeks ago which just makes sure the other define types default to being created under the appropriate directories.
- It also updates the tests for the ido objects and changes the titles of some file resources so they're consistent with the other define types.

### CODE REVIEW

**Comment by Reamer** [comment]
:+1:

**Comment by Reamer** [comment]
Hi Ziaunys,
i have tested your patch and there are some mistakes.

The right path should be:
'/etc/icinga2/objects/idomysqlconnection**s**'
'/etc/icinga2/objects/idopgsqlconnection**s**'
'/etc/icinga2/objects/service**s**'

This folders are created in this file: https://github.com/Icinga/puppet-icinga2/blob/develop/manifests/config.pp#L51

Greetings Reamer

**Comment by Ziaunys** [comment]
Thanks for catching that. I went and fixed those paths.

**Comment by arioch** [comment]
Excellent!
Merged upstream.

**Pull request closed without merging**
