### PR TITLE
Added possibility to define command_endpoint for services.

### PR DESCRIPTION
**Pull request by aschaber1**

### CODE REVIEW

**Comment by arioch** [comment]
Looking good so far.
Could you also add a little spec test to cover this?

**Comment by erikanderson** [comment]
+1 for this

**Comment by bwolf** [comment]
Please add this, otherwise we would have to misuse apply service to achive the same result.

**Comment by erikanderson** [comment]
In `spec/defines/icinga2__object/service_spec.rb` I think this block should work: 

```
  context "with parameter command_endpoint" do

    let(:title) { 'testservice' }

    let(:params) do
      {
        :object_servicename => 'testservice',
        :display_name => 'testservice',
        :target_file_name => 'testservice.conf',
        :command_endpoint => 'testservice.example.com'
      }
    end

    object_file = '/etc/icinga2/objects/services/testservice.conf'
    it { should contain_icinga2__object__service('testservice') }
    it { should contain_file(object_file).with({
          :ensure => 'file',
          :path => '/etc/icinga2/objects/services/testservice.conf',
          :content => /template Service "testservice"/,
        }) }
    it { should contain_file(object_file).with_content(/^\s*import "generic-service"$/) }
    it { should contain_file(object_file).with_content(/^\s*command_endpoint "testservice.example.com"$/) }

  end
```

@Uranellus @arioch 

My branch: https://github.com/Icinga/puppet-icinga2/compare/develop...erikanderson:service_command_endpoint_spec

**Comment by arioch** [comment]
Duplicate from 4de73176484c93d5cfde58f2819f640206a4572f.
Closing because it's already merged.

Thanks again guys.

**Pull request closed without merging**
