### PR TITLE
Add apply scheduled downtimes support

### PR DESCRIPTION
**Pull request by nerzhul**

### CODE REVIEW

**Comment by arioch** [comment]
Looking good so far.
Would you mind adding a little snippet to readme.md and a spec test to cover this feature?

**Comment by nerzhul** [comment]
@arioch i will work on the README.md tomorrow. For test it don't know how to test it i'm not familiar with spec tests :(

**Comment by arioch** [comment]
@nerzhul excellent. :+1: 

In the spec/ folder you'll find a number of examples.
F.i. [icinga2::object::apiuser](https://github.com/Icinga/puppet-icinga2/blob/develop/spec/defines/icinga2_object_apiuser_spec.rb). This one should be pretty close to what you'd need.

You can run the tests by running: `bundle; bundle exec rake spec`. 
Or `bundle; bundle exec rspec spec/defines/icinga2_object_ apply_scheduleddowntime_spec.rb` to run just your test.

However if you don't feel like writing a test that's ok too, no worries. 
It will just take us longer to merge this PR as we'd need to do it ourself.

**Comment by nerzhul** [comment]
@arioch documentation added

**Comment by arioch** [comment]
Bonus points for rebasing. :smile:

**Comment by lazyfrosch** [comment]
Like it, :+1: 

Just two remarks that I will change:
1. I'd prefer this, and escape it properly `apply => 'Service'`
2. I want to avoid all the target_\* stuff and make it simpler, like in `icinga2::object::zone`

**Comment by nerzhul** [comment]
@lazyfrosch will look at this soon :)

**Pull request closed without merging**
