### PR TITLE
Purge unmanaged files from nrpe.d

### PR DESCRIPTION
**Pull request by arioch**
With this patch anything inside /etc/nagios/nrpe.d/ that is not managed by Puppet will be removed.

### CODE REVIEW

**Comment by smbambling** [comment]
What about also purging items from /etc/nrpe.d just as an extra precaution ?

**Comment by arioch** [comment]
@cropalato: would you like the default to leave the files as-is with the option to enable it? Or the other way around?

@smbambling: good point. I'll add it too.

**Comment by nickchappell** [comment]
@arioch I'd prefer the parameter to default to leaving things as-is. It would be the least surprising behavior. Also, could you add a section to the README explaining the parameter (including default behavior) and showing a usage example?

**Comment by smbambling** [comment]
Agreed the last thing you want to do is have someone unknowingly break their monitoring infrastructure.  Especially if they are transitioning to using the module

**Comment by arioch** [comment]
That's fixed in 22770bf232b6abaeba14602a5e0fb2ff31386df9.

**Comment by arioch** [comment]
Anything else needed to get this merged?

**Comment by nickchappell** [comment]
Hi @arioch,

Would you be able to add the `nrpe_purge_unmanaged` to the parameter list of the `icinga2::nrpe` class and make its default value the value of `nrpe_purge_unmanaged` in `params.pp`? Right now, it can't actually be set.

**Comment by arioch** [comment]
My bad, I was expecting it to be inherited from ::icinga2::params.
Should be fixed now.

**Comment by nickchappell** [comment]
Just for reference, create a [dev.icinga.org](https://dev.icinga.org) issue: [#7673](https://dev.icinga.org/issues/7673)

**Comment by nickchappell** [comment]
Merged. Thanks @arioch, @cropalato and @smbambling!

**Pull request closed without merging**
