### PR TITLE
Refactor and move config handling

### PR DESCRIPTION
**Pull request by lazyfrosch**
There should not be any impact, because icinga2::server::config was not meant
to be called directly.

### CODE REVIEW

**Comment by lazyfrosch** [comment]
https://dev.icinga.org/issues/8216

**Comment by nickchappell** [comment]
I actually had this in progress locally (hadn't committed anything) as a part of making a more generic `icinga2::node` class. Would it be OK to hold off on this change until that's complete?

**Comment by lazyfrosch** [comment]
Wouldn't it easier to go step by step?

My change is quite trivial, as it does not affect the way it works, just the code quality :)

**Comment by lazyfrosch** [comment]
I can rebase if you want to merge :)

**Comment by lazyfrosch** [comment]
Merged into develop under ccd9626

**Pull request closed without merging**
