### PR TITLE
Added the possibility to reload Icinga2 when the service receives a notification

### PR DESCRIPTION
**Pull request by Reamer**
Hi,

i think we should give the possibility to use the advantages of reloading icinga2.

Greetings Reamer

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Thanks for your PR.

Basically this is a good idea, I see 2 problems:
- there is no real good way of reloading a Puppet service, that works across platforms
- Icinga2 internally does a restart every time

There is no real sense to signal a reload.

What was important to me is that we check the config internally before triggering a restart.

The only benefit I can see is that the reload is a bit faster internally, because Icinga2 makes the hand over.

@arioch @dnsmichi your thoughts?

**Comment by arioch** [comment]
We've discussed this before in an earlier ticket. Can't seem to find which one exactly.
However @lazyfrosch has summarised the gist of it. Especially the lack of cross platform support is troublesome.

I've had setups with +3000 line config files reload in a matter of seconds.
I don't see any added value in a reload over a restart.

**Comment by dnsmichi** [comment]
Icinga2 does not do a restart when a SIGHUP is sent. It instead forks a child process which validates the configuration and signals the parent process when it is ready to take over. In the meantime the parent process continues to execute checks, send/receive cluster events, etc. 

When the child wants to take over uppn successful config load, the parent process shuts down, writes its state file, and the child reads its history. That way the downtime is not measurable, and helps a lot in large scale systems.

The old fashioned "restart" is just a plain dumb SIGKILL and the start the daemon again. Which means that the config validation & compiling could take longer (some instances with 100k objects will take e.g. a couple of minutes to do just that). The downtime window being unable to do checks or communicate in the cluster is quite longer.

So the feature request to issue a reload is totally valid. Though I don't know how to implement that cross-/multi-platform with Puppet.

**Comment by Reamer** [comment]
The lack of cross platform support is not the task of this module,it's a task for puppet. But I think we should give the opportunity to people, who would like to reload the icinga2 instance. When i read this [documentation](http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/migration#differences-1x-2-real-reload) it sounds that some people have problem with a normal restart.

I'm new in icingaweb2 dashboard, but i see some interesting stuff. You can add comments with no persistence until icinga2 is restarted. I test this functionality with reload, restart and stop/start but the comment is still there. Maybe sometimes it works. A restart would delete this comment, but a reload hopefully not. Especially when we add/remove dynamical configuration with puppet a restart is not helpful.

**Comment by arioch** [comment]
I accidentally closed this discussion, I meant to just comment. 
My apologies for that.

**Comment by lazyfrosch** [comment]
@dnsmichi agreed, but there is no clean way to do it with Puppet.

Usually a restart is enough, and the config is validated before to make sure it works.

The problem remains is the time gap of shutdown and config test to bring up the new daemon. In the Puppet world, all software managed by Puppet has that problem, e.g. Apache.

If someone comes up with a good solution, I'd consider it, `restart_cmd => 'service icinga2 reload'` is not enough, sorry.

**Comment by Reamer** [comment]
@dnsmichi 
I know there is no clean way. There are several puppet module, with workarounds. The best one is [puppet/postgresql](https://github.com/puppetlabs/puppetlabs-postgresql/blob/master/manifests/server/config_entry.pp)

They default behaviour is still the normal restart, but for big icinga2 instance (master Server) we should give the possibility to reload the service.
I know it's not a good way to override the restart_cmd but it's better then nothing.

A other example is this module [mayflower/php](https://github.com/mayflower/puppet-php/blob/master/manifests/fpm/service.pp). Here is the default behaviour to reload the service.

Greetings Reamer

**Comment by lazyfrosch** [comment]
Okay, I'll give it a try in a test environment. I guess `service` should be working on all the distros we want to support.

Regarding config test, Puppet should actually be able to see that the config is newer than the daemon, since the reload won't update the PID file when the reload failed for whatever reason.

**Comment by Reamer** [comment]
rebase of commit, because PR is two month old.

**Comment by lazyfrosch** [comment]
Am I wrong or have you changed it so there is no default reload_cmd set?

**Comment by Reamer** [comment]
there is a default in params.pp 

```
$restart_cmd = undef
```

**Comment by lazyfrosch** [comment]
Merged, thanks for your contribution

**Pull request merged**
