### PR TITLE
Adding StatusDataWriter object. #7223

### PR DESCRIPTION
**Pull request by cropalato**

### CODE REVIEW

**Comment by nickchappell** [comment]
Just for reference,  [#7223](https://dev.icinga.org/issues/7223) is the [dev.icinga.org](https://dev.icinga.org) issue.

**Comment by nickchappell** [comment]
Hi @cropalato, the patch for this won't apply because the README has diverged from the state it was in when you made the PR (I've merged a few other PRs tonight). Would you be able to rebase the current master onto your feature branch and re-push?

This page is a good overview on how to do that: https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#how-do-i-rebase

**Comment by cropalato** [comment]
should be ok now.

**Comment by nickchappell** [comment]
Hi @cropalato,

I tried testing this out with the usage example you had in the README but there's an inconsistency with the `object_path` parameter. It's listed as `objects_path` in the defined type's manifest but is listed as `objects_path` elsewhere (README, the ERB template, etc.).

**Comment by cropalato** [comment]
Fixed typo

**Comment by nickchappell** [comment]
Merged this in. Thanks @cropalato!

**Pull request merged**
