### PR TITLE
update zone documentation. enpoints are no arrays, they are hashes now

### PR DESCRIPTION
**Pull request by rwaffen**

### CODE REVIEW

**Comment by gunnarbeutner** [comment]
The 'endpoints' attribute is actually _not_ a dictionary. It's an array and apparently the Icinga 2 documentation incorrectly states that it's a dictionary.

**Comment by rwaffen** [comment]
Than why is there a validate_hash and create_resource in the code. I didn't get it to work with arrays.

manifests/object/zone.pp

```
  if $endpoints {
     validate_hash($endpoints)
     $_endpoints = keys($endpoints)

     create_resources('icinga2::object::endpoint', $endpoints)
}
```

**Comment by dgoetz** [comment]
Sorry, guys, you are talking apples and oranges.

In Icinga 2 the attribute endpoints of the zone object is an array, but in the puppet module it is a dictionary to provide additional attributes to also create the endpoint objects automatically.

**Comment by rwaffen** [comment]
oh okay, that's the point... was wondering how that would be an array in puppet when it is checked that it has to be a hash 😄

**Comment by arioch** [comment]
Excellent. 👍 
Merged upstream.

**Pull request closed without merging**
