### PR TITLE
apply notification to service / host fix

### PR DESCRIPTION
**Pull request by vanveele**
Fixes a template variable typo. There also appears to be an incomplete validation regex for interval param.

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi,

Thanks for the PR. Just wanted to give you a heads up that I'll be traveling with family for a little while and may not able to review/merge this until after Christmas.

**Comment by nickchappell** [comment]
Created a [dev.icinga.org](https://dev.icinga.org) issues: [#8155](https://dev.icinga.org/issues/8155)

**Comment by nickchappell** [comment]
Hi @vanveele,

Could you rebase and squash this against the current develop branch?

**Comment by vanveele** [comment]
typo was already fixed in develop branch and also uses validate_string instead of validate_re which fixes error

**Pull request closed without merging**
