### PR TITLE
WIP: FreeBSD support

### PR DESCRIPTION
**Pull request by zachfi**
This work takes a first pass over adding support for the FreeBSD
platform.

### CODE REVIEW

**Comment by zachfi** [comment]
The configuration directory here for icinga2 on FreeBSD should be `/usr/local/etc/icinga2`, but currently its not configurable.  How would folks like this to be addressed?  I'm happy to make the config directory tunable, but its hardcoded in lots of places currently, so before I embark on such a task, I'd like to see if there is a preferred way to handle this.  I know the defaults everywhere else are for `/etc/icinga2`, but since we don't deploy all files we include, the service remains broken on FreeBSD.

**Comment by zachfi** [comment]
@arioch @lazyfrosch Any thoughts here as to adding support for FreeBSD?

**Comment by lazyfrosch** [comment]
@xaque208 if you have a proper test setup, go ahead!

:+1: for config_dir support

**Comment by arioch** [comment]
What's the current status of this WIP?
I see some overlap with #196. Does this cover what you need?

**Comment by zachfi** [comment]
Once the prefix stuff is in place, I can begin adding support.  On my personal infrastructure, I've symlinked the directories and the module works quite well, so all that is required for FreeBSD support is:
- remove any root group use and replace with '0'
- Any configuration paths prefixed with `/usr/local`
- Tests to keep this from regressing

I think thats it really.  I'll take a pass over #196 again.

Puppet4 native data in modules would make this quite a bit simpler.  Did you see my report I filed about it on the ticket tracker?

**Comment by zachfi** [comment]
Looks like the module is being rewritten.  No need to keep this open.

**Pull request closed without merging**
