### PR TITLE
Added  support for Debian 8 (Jessie)

### PR DESCRIPTION
**Pull request by georgemihalcea**
Tested with Debian 7 and Debian 8 and it is working on both.
For Debian 8, packages 'icinga*' from debmon are pinned with priority 500, and default pin priority for debmon repository is 300.

### CODE REVIEW

**Comment by arioch** [comment]
Thanks for the contrib!

Given the fact this is the official Icinga2 module I'd prefer to have the upstream [Icinga repository](http://packages.icinga.org/debian/dists/icinga-jessie/main/binary-amd64/Packages) in the module instead of Debmon's.

**Comment by georgemihalcea** [comment]
You're welcome!

Well, I could change that, if you want me to. I used debmon for Debian Jessie because it was already like this for Debian Wheezy. I could change the repository for both Jessie and Wheezy, I see there are packages for both in Icinga repository. Or should I just add also Icinga repository and also leave debmon repository as an option (for backwards compatibility at least, I assume there are a lot of people that already use this module)?

I'll also try to implement it in the develop branch when I have some time.

**Comment by arioch** [comment]
I've just noticed `if $use_debmon_repo == true {}` in the code.
I think like you said adding upstream next to Debmon as an option is the way to go.

If possible send PR's to develop instead of master.

**Comment by georgemihalcea** [comment]
Sure, I'll change to develop, but it will take me a little more time. There are some changes to do for that and I do not have time right now. 

I'll create the PR when I'm done. 

Thanks for your quick answers!

**Comment by formorer** [comment]
On Thu, 18 Jun 2015, Tom De Vylder wrote:

> Thanks for the contrib!
> 
> Given the fact this is the official Icinga2 module I'd prefer to have the upstream [Icinga repository](http://packages.icinga.org/debian/dists/icinga-jessie/main/binary-amd64/Packages) in the module instead of Debmon's.
> The official one is the debmon one. 

We usually don't recommend using packasges.icinga.org in production.

alex

**Comment by lazyfrosch** [comment]
I agree with preferring debmon as main repo, if someone wants to use latest packages.

What I don't like is the pinning, could you please remove that?

And is there any reason why to duplicate the `apt::source { 'debmon':` ?

**Comment by georgemihalcea** [comment]
I changed the code to remove pinning for Debian 8, but kept if for Debian 7 (because it was already there). To avoid the duplicated `apt::source { 'debmon':` I had to put more conditions in the code, but I think it is ok now. The idea was to have separate code for debian 7 and debian 8, that is what the resource was duplicated before.

I also changed the key for debmon repository to avoid this warning:
`Warning: /Apt_key[Add key: 29D662D2 from Apt::Source debmon]: The id should be a full fingerprint (40 characters), see README.`

I guess this PR could be integrated in `master`, because already Debian 8 is for some time released.
I'll also create another PR for `develop` branch for this.

**Comment by arioch** [comment]
Closing this one as I've merged your other PR (#109). :+1: 
Thanks again!

**Comment by georgemihalcea** [comment]
You're welcome!

**Pull request closed without merging**
