### PR TITLE
F apply notification to service

### PR DESCRIPTION
**Pull request by smbambling**
Defined type to create a 'apply' notification object to a service. Includes updated README with PagerDuty example.

### CODE REVIEW

**Comment by nickchappell** [comment]
Created a [dev.icinga.org](https://dev.icinga.org) issue: [#7677](https://dev.icinga.org/issues/7677)

**Comment by nickchappell** [comment]
Hi @smbambling , the patch for this won't apply. I've merged a few other PRs tonight, probably making this one stale. Would you be able to rebase the current master onto your feature branch and re-push?

**Comment by smbambling** [comment]
@nickchappell: Ok this is complete ..it was just a merge conflict with the README markdown file that was causing the merge issues.

**Comment by nickchappell** [comment]
Merged this in. Thanks @smbambling!

**Pull request closed without merging**
