### PR TITLE
add template options

### PR DESCRIPTION
**Pull request by moritzfriedrich**
add template option for:
     - service
     - host
     - user

fixed missing quotes in command
     - checkcommand.conf.erb
     - notificationcommand.conf.erb
also moved cmd_path into thee each-loop to append with each command, else only the first command will work as expected

### CODE REVIEW

**Comment by janvonde** [comment]
Please merge this, I'd love to use this functionality.

**Comment by arioch** [comment]
Could you rebase this into a single commit? (`git rebase -i ...  => pick => fixup`)

**Comment by moritzfriedrich** [comment]
All changes should be in my last commit, now https://github.com/moritzfriedrich/puppet-icinga2/commit/30001482d694d69987c24974f444d2d6154b5d85

**Comment by arioch** [comment]
I'm still seeing 11 commits: https://github.com/Icinga/puppet-icinga2/pull/178/commits
And 3 commits when manually rebasing your changes onto current state. So please pull in the latest commits and rebase your remaining ones into a single one.

Furthermore it would be awesome if you could add some spec tests and a little documentation too.

**Comment by moritzfriedrich** [comment]
@arioch Can you help me? Now there is my commit with my changes, and two merge commits. How can I merge them? `git rebase -i` didn't work.

I will have a look into the spec tests and documentation later.

**Comment by arioch** [comment]
No worries, we'll get you through this.

Could you send me the output of `git pull --rebase $remote develop`? 
Be sure to adjust `$remote` to match your particular setup.

**Comment by moritzfriedrich** [comment]
@arioch Thank you :)
The output is:

> From github.com:moritzfriedrich/puppet-icinga2
> - branch            develop    -> FETCH_HEAD
>   Current branch is_template_option is up to date.

**Comment by arioch** [comment]
I should've been more clear in my last message:
`$remote` being the remote that points to `Icinga/puppet-icinga2.git`, not your fork.

**Comment by moritzfriedrich** [comment]
Ahh. Thank you. Something new that I`ve learned. Now it`s one commit as expected.
Previously I always used the develop branch of my fork for rebasing.

**Comment by arioch** [comment]
Excellent! :+1: 
Regarding the spec tests: do you have any prior experience?
If not it's not as scary as it looks. I can guide you through that step as well.

**Comment by moritzfriedrich** [comment]
Yes, i`m familiar with spec tests. I included them for all of my changes.

**Comment by arioch** [comment]
Excellent. :+1: 
Thanks again!

Merged upstream.

**Comment by janvonde** [comment]
thanks @moritzfriedrich and @arioch!

**Pull request closed without merging**
