### PR TITLE
Notify nrpe daemon when config changes

### PR DESCRIPTION
**Pull request by arioch**
Quite trivial: when any nrpe related config changes the daemon should be restarted.

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi @arioch,

Could you make this a parameter (defaulting to refresh the daemon is fine)?

**Comment by arioch** [comment]
This should do the trick.
I've rebased it into a single commit.

**Comment by arioch** [comment]
I've noticed similar functionality for the Icinga2 daemon was added just recently so I've renamed the nrpe parameter for sake of consistency.

```
-  $nrpe_daemon_notify = true
+  $refresh_nrpe_service = true
```

**Comment by lazyfrosch** [comment]
I don't see a notify connection for `file { "/etc/nagios/nrpe.d/${command_name}.cfg":` anymore, did you miss something while commiting?

**Comment by lazyfrosch** [comment]
Ah I see what you've done, but that would not work, you will have to use `File {}` before declaring the other classes, or it will not work.

Please but that into config.pp and the command.pp, I think thats cleaner.

**Comment by arioch** [comment]
Global resource defaults apply to subclasses as well.
In this case File {} within nrpe will apply to nrpe::command, nrpe::config, nrpe::install, nrpe::plugin and nrpe::service.

Let me know if you still prefer to have it in config.pp and command.pp.

**Comment by lazyfrosch** [comment]
I thought such defaults are required _above_ deeper includes/declarations to work.

Yes I would prefer that, because a user would not look in init.pp for such a definition. IMHO

**Comment by arioch** [comment]
Here you go.

**Comment by lazyfrosch** [comment]
Sorry, found another `$::icinga2::nrpe_daemon_name` must be `$::icinga2::nrpe::nrpe_daemon_name`, or even better `$::icinga2::nrpe::daemon_name`

**Comment by arioch** [comment]
This should do it then.

**Comment by nickchappell** [comment]
I merged this in. Thanks @arioch!

**Pull request closed without merging**
