### PR TITLE
Adding CompatLogger object. #7225.

### PR DESCRIPTION
**Pull request by cropalato**
https://dev.icinga.org/issues/7225

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi @cropalato,

Did you also have an accompanying ERB template to include?

**Comment by cropalato** [comment]
@nickchappell,

Not sure if i understood. the erb template is there. templates/object_compatlogger.conf.erb. I'm changing 3 files (README, class and template)

**Comment by nickchappell** [comment]
Derp, I see it now. I hadn't yet had my afternoon tea. :)

**Comment by cropalato** [comment]
;-)

**Comment by nickchappell** [comment]
Hi @cropalato,

Last night, I pushed up a develop branch. To keep the master branch reasonably stable, I'd like to add features and fixes to the develop branch instead of master. Would you be able to resubmit this against the develop branch?

**Comment by cropalato** [comment]
HI @nickchappell ,
moved

**Pull request closed without merging**
