### PR TITLE
Sytle Guide and Case Fixes

### PR DESCRIPTION
**Pull request by smbambling**
Just doing a little style cleanup based on puppet-lint and also adding some defaults to the db_type cases to be consitent within the module

### CODE REVIEW

**Comment by smbambling** [comment]
update to case statement may trigger a failure, doing more testing

**Comment by nickchappell** [comment]
@smbambling,

Did you find any issues?

**Comment by smbambling** [comment]
@nickchappell nope upon further testing I didn't find any issues with the changes.  Sorry for the close I just wanted to be overly sure.

**Comment by nickchappell** [comment]
Merged. Thanks @smbambling!

**Pull request closed without merging**
