### PR TITLE
Add independent check plugin defined type

### PR DESCRIPTION
**Pull request by smbambling**
This defined type is independent of NRPE to make it less confusing when using other client that reference the check plugins (scripts) or check plugins (scripts) that are not used via NRPE but executed locally from the Icinga 2 Core node.

Created a new parameter $checkplugin_libdir   = '/usr/lib/nagios/plugins' to keep backwards compatibility with the nrpe::plugins manifest.

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi @smbambling,

Is this for allowing a user to upload their own executable plugin script that the Icinga 2 core would run?

**Comment by smbambling** [comment]
Yes or any client NRPE,NSClient++,ect...

**Comment by nickchappell** [comment]
Would you be able to add support for static files in addition to the template sources?

**Comment by smbambling** [comment]
I think that is possible, with a parameter switch to set which you would like to use source vs content.

Though I'd make the argument for using templates for this case even when having a "static" file when only a single file (excluding binary files)is being managed by a define or class.
- It seems more tidy when not having to mix both static files and templates in a module.  
- Templates are shipped with the catalog and can be used with remote systems that can't access access the Puppet Master/Server file share ( Applied Offline )
- Gives you the flexibility of adding referenced syntax without having to modify the define/class of the module
- Less security management with the puppet file server

There are a few downfalls which IMO are not a concern with this module.
- Templates do put more load on your master for catalog compilation then service static files
- Templates do not support serving 'recursive' File resources

That said if required I'll work on modifying the define to allow using either the file server or templates to serve the file.

**Comment by nickchappell** [comment]
I think the option of using either a template or a static file source would be best.

**Comment by smbambling** [comment]
This has been updated to allow for either using a template or a static file via the file server.

**Comment by nickchappell** [comment]
Merged this in. Thanks @smbambling!

**Pull request closed without merging**
