### PR TITLE
Fix notificationcommand template

### PR DESCRIPTION
**Pull request by n00by**
Make sure the "command" parameter is passed as an array to the
"each_with_index" method, otherwise an exeption is thrown.

Minor syntax corrections.

### CODE REVIEW

**Comment by arioch** [comment]
Could you also adjust the spec tests?

**Comment by n00by** [comment]
done

**Comment by n00by** [comment]
@arioch please bump

**Comment by arioch** [comment]
Thx @n00by, very much appreciated as always. 👍

**Pull request closed without merging**
