### PR TITLE
Improving RedHat support

### PR DESCRIPTION
**Pull request by alexxxxx**
Signed-off-by: Alexandre Beche alexandre.beche@gmail.com

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi @alexxxxx,

@marxst opened up a separate PR for this, #83. Would you mind  working with @marxst to coordinate your changes?

**Comment by marxst** [comment]
Hi @alexxxxx,
I would like to replace my regex case statements with your comma separated list cases and get rid of the duplicate code fragments I produced. 
Though I am just a git newbie, I think the correct way would be to merge your branch into my one, solve the conflicts and push the results back?

**Comment by alexxxxx** [comment]
Hello,

I don't exactly know when you fork the code (and from which branch) but I
got a PR merged to develop branch which already modify the params.pp (sha
of the commit being: bb523a9dc616854d64f567d43e619747e90fc2be).

That said, I would recommend you to to rebase your change on that commit on
develop branch and merge. Then either you or I can re-apply the new change
I just did which is just adding , 'RedHat' in server.pp.

Cheers,
Alex

**Comment by marxst** [comment]
Hi,
Ok, I will try to figure this out ;-) . Just did the same change on params.pp and server/install.pp
Cheers, Stefan

On 15 Jan 2015, at 18:50, abeche <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

I don't exactly know when you fork the code (and from which branch) but I
got a PR merged to develop branch which already modify the params.pp (sha
of the commit being: bb523a9dc616854d64f567d43e619747e90fc2be).

That said, I would recommend you to to rebase your change on that commit on
develop branch and merge. Then either you or I can re-apply the new change
I just did which is just adding , 'RedHat' in server.pp.

Cheers,
Alex

On Thu, Jan 15, 2015 at 6:18 PM, Stefan Marx <notifications@github.com<mailto:notifications@github.com>>
wrote:

> Hi @alexxxxx https://github.com/alexxxxx,
> I would like to replace my regex case statements with your comma separated
> list cases and get rid of the duplicate code fragments I produced.
> Though I am just a git newbie, I think the correct way would be to merge
> your branch into my one, solve the conflicts and push the results back?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/Icinga/puppet-icinga2/pull/80#issuecomment-70122784.

##

**Comment by nickchappell** [comment]
#83 got merged in, so I'll close this PR.

**Pull request closed without merging**
