### PR TITLE
Add define type and template for the Icinga2 zone object.

### PR DESCRIPTION
**Pull request by Ziaunys**
- This commit adds a new define type in order to create Icinga2 zone objects in the managed objects directory. I've tried to follow the pattern of the other object define types.

### CODE REVIEW

**Comment by arioch** [comment]
Thanks! Looks great so far.
Would you mind adding a little rspec and an example to the readme?

**Comment by Ziaunys** [comment]
Sure thing. I'd love to add more tests where needed.

**Comment by Ziaunys** [comment]
I've added an rspec test and updated the documentation. The build seems to be failing, but it seems unrelated.

**Comment by arioch** [comment]
Well actually it's a lintian error.
If you add `# == Defined type: icinga2::object::zone` to the top of manifests/object/zone.pp it's fixed.

However all zone tests fail and seem to be Debian Wheezy only instead of Debian, Ubuntu & RHEL.

```
Failures:

  1) icinga2::object::zone on default Debian wheezy with basic parameters should contain File[/etc/icinga2/objects/testzone.conf] with ensure => "file", path => "/etc/icinga2/objects/testzone.conf" and content =~ /object Zone "testzone"/
     Failure/Error: it { should contain_file(object_file).with({
       expected that the catalogue would contain File[/etc/icinga2/objects/testzone.conf]


     # ./spec/defines/icinga2_object_zone_spec.rb:30:in `block (3 levels) in <top (required)>'

  2) icinga2::object::zone on default Debian wheezy with basic parameters should contain File[/etc/icinga2/objects/testzone.conf] with content =~ /^\s*endpoints = \["endpoint1", "endpoint2",\]$/
     Failure/Error: it { should contain_file(object_file).with_content(/^\s*endpoints = \["endpoint1", "endpoint2",\]$/) }
       expected that the catalogue would contain File[/etc/icinga2/objects/testzone.conf]
     # ./spec/defines/icinga2_object_zone_spec.rb:35:in `block (3 levels) in <top (required)>'

  3) icinga2::object::zone on default Debian wheezy with parent should contain Icinga2::Object::Host[testzone]
     Failure/Error: it { should contain_icinga2__object__host('testzone') }
       expected that the catalogue would contain Icinga2::Object::Host[testzone]
     # ./spec/defines/icinga2_object_zone_spec.rb:60:in `block (3 levels) in <top (required)>'

  4) icinga2::object::zone on default Debian wheezy with parent should contain File[/etc/icinga2/objects/testzone.conf] with ensure => "file", path => "/etc/icinga2/objects/testzone.conf" and content =~ /object Zone "testzone"/
     Failure/Error: it { should contain_file(object_file).with({
       expected that the catalogue would contain File[/etc/icinga2/objects/testzone.conf]
     # ./spec/defines/icinga2_object_zone_spec.rb:61:in `block (3 levels) in <top (required)>'

  5) icinga2::object::zone on default Debian wheezy with parent should contain File[/etc/icinga2/objects/testzone.conf] with content =~ /^\s*endpoints = \["endpoint1", "endpoint2",\]$/
     Failure/Error: it { should contain_file(object_file).with_content(/^\s*endpoints = \["endpoint1", "endpoint2",\]$/) }
       expected that the catalogue would contain File[/etc/icinga2/objects/testzone.conf]
     # ./spec/defines/icinga2_object_zone_spec.rb:66:in `block (3 levels) in <top (required)>'

  6) icinga2::object::zone on default Debian wheezy with parent should contain File[/etc/icinga2/objects/testzone.conf] with content =~ /^\s*parent = "testmaster"$/
     Failure/Error: it { should contain_file(object_file).with_content(/^\s*parent = "testmaster"$/) }
       expected that the catalogue would contain File[/etc/icinga2/objects/testzone.conf]
     # ./spec/defines/icinga2_object_zone_spec.rb:67:in `block (3 levels) in <top (required)>'

Finished in 10.56 seconds (files took 0.89816 seconds to load)
119 examples, 6 failures, 2 pending
```

**Comment by Ziaunys** [comment]
The PR has been updated and the tests pass now.

**Comment by arioch** [comment]
That did the trick. :+1: 
Merged upstream.

Thanks again! Keep those PR's coming.

**Pull request closed without merging**
