### PR TITLE
Adding hash support for vars values in object::host

### PR DESCRIPTION
**Pull request by TheBigLee**
Added routine for cases where the value of a vars variable is a hash.

### CODE REVIEW

**Comment by nickchappell** [comment]
Just wanted to give you a heads up that I'll be traveling with family for a little while and may not able to review/merge this until after Christmas.

**Comment by pdirksen** [comment]
Without this patch object::host is pretty much useless because you can't specify the contents of the vars variable right now. Thanks

**Comment by nickchappell** [comment]
Created a [dev.icinga.org](https://dev.icinga.org) issues: [#8156](https://dev.icinga.org/issues/8156)

**Comment by nickchappell** [comment]
Merged this in. Thanks @Bigluu!

**Pull request closed without merging**
