### PR TITLE
Adding template to activate statusdata and compatlog

### PR DESCRIPTION
**Pull request by plarivee**
Those were missing to be able to use

 icinga2::features::load {'compatlog':}
  icinga2::features::load {'statusdata':}

*\* Forget me for the multiple commits, tried to squash them but I also tried to be up to date with the develop branch. Made kinda of a mess of things once merge. ###

### CODE REVIEW

**Comment by zachfi** [comment]
Would you mind squashing down those commits?  For users to know those features are something they want to enable, maybe a documentation update here as well.

**Comment by plarivee** [comment]
@xaque208 I tried squashing down but my git foo is weak, I'll try fixing. Also I'll try to add on the documentation.

**Comment by erikanderson** [comment]
You can squash using `git reset --soft` like this:

```
git reset --soft HEAD~$number_of_commits_to_squash
git commit -m "$commit_message"
git push origin current_branch --force
```

**Comment by plarivee** [comment]
Closing this PR since https://github.com/Icinga/puppet-icinga2/commit/58e822e6351331b2595d0c9a3e4874d2bc8195ee  removed features.pp  on what this PR was based to load features.   will need to recheck the new way .

**Pull request closed without merging**
