### PR TITLE
WIP: Major refactoring

### PR DESCRIPTION
**Pull request by lazyfrosch**
Hey all,
we are doing some refactoring work to raise the overall quality of the module and offer better functionality.

This change should happen with a release of 1.0.0. But it will also introduce some breaking changes, like parameter names being changed, and possibly switching from `icinga2::server` and `icinga2::node` to `icinga2` as the main class.

Check our RedMine, if you'd like to contribute or see what we are doing:
https://dev.icinga.org/projects/puppet-icinga2
or
https://dev.icinga.org/projects/puppet-icinga2/roadmap

If you see a point in fixing adding or fixing small stuff in 0.x please open a ticket or PR against `master`.

For contributing to the new code, use `develop` as a base.

### CODE REVIEW

**Comment by tarjei** [comment]
Hi, can you change this to be a branch so it is testable?

**Comment by tarjei** [comment]
i.e. by people outside the project :)

**Comment by arioch** [comment]
@tarjei it's already on the develop branch

**Comment by lazyfrosch** [comment]
@tarjei this PR is just here for visibility

**Comment by tarjei** [comment]
Great! :+1:

**Comment by tarjei** [comment]
Hi, I'm sorry for hijacking this thread, but it seems to be the easiest place to discuss and ask questions about this module.

Why does the module spend so much time on handling NRPE but seems to forget the option of using icinga2 as a client?

**Comment by lazyfrosch** [comment]
NRPE has been inside the module from the beginning, before we had a the agent in Icinga 2, we might remove it in the future.

**Comment by arioch** [comment]
@lazyfrosch what's the current status of your refactor?
Is this ready to be merged?

**Comment by lazyfrosch** [comment]
Well, I don't have much time at the moment, so it will take some time. Should we do a Hangout soon?

**Comment by tarjei** [comment]
Hi, I know this is probably the wrong place for this, but I think it would be great if you moved issuehandling for the puppet module to github. 

Also, I would love to se some support for ichinga2 as a client in puppet :)

**Comment by dnsmichi** [comment]
Put your feature request(s) and bug reports onto https://dev.icinga.org please. Either all icinga projects are organized at github, or none - that discussion comes up from time to time. Feel free to discuss on the community support channels then.

**Comment by zachfi** [comment]
When is this expected to land?  We'd love to start using the module, but not in its current form, and this branch seems to be headed in the right direction.  I'd really like to avoid forking and then merging it all out later if we can, but we're itchy to get started on our deployment of icinga2.

**Comment by lazyfrosch** [comment]
@xaque208 thanks for your interest, unfortunately my time is pretty limited currently.

There is no plan on a release date yet. If you like to work on the module, share us your ideas in issues and PRs - https://dev.icinga.org/projects/puppet-icinga2/roadmap

**Comment by joshbeard** [comment]
@arioch 20690703c883ae3bc7f185311b92359192f457bb broke NRPE.  Looks like the template (https://github.com/Icinga/puppet-icinga2/blob/develop/templates/nrpe.cfg.erb#L41) references `icinga2::nrpe::nrpe_pid_file_path`, which is no longer a valid variable.  Previously, this was inherited from `params`, but the params inheritance was removed in this commit.  Not sure how you want to proceed - inherit params in `icinga2::nrpe` or add that as a parameter with a default from the base class?

**Comment by arioch** [comment]
@joshbeard I'll check tomorrow at the office. 
I was planning to fix this today but some other stuff came inbetween.
Thanks for the insight btw, it's exactly what I need to fix it. :+1:

**Comment by walterheck** [comment]
Can this please be merged to production branch asap? 9 months for a fork that became the de-facto production branch is pretty bad imho.

**Comment by lazyfrosch** [comment]
This PR has one lonely purpose, informing people about the state. But obviously thats too irritating, so im closing this.

If you wanna help out:
https://dev.icinga.org/projects/puppet-icinga2/roadmap

**Comment by walterheck** [comment]
wait, so all the work in this PR is not going to be merged?

**Comment by lazyfrosch** [comment]
This PR is just a virtual notice to merge `develop` into `master` nothing else.

**Comment by walterheck** [comment]
certainly closing the PR because it's inconveniently showing a problem is not the way to make the problem go away? It'll just confuse people more to find a branch that's 160+ commits different then production.

**Comment by LorenzBischof** [comment]
What are your plans concerning putting this on forge? It seems the commits have slowed down in the last few weeks and I would really like to use this in production in a few months.

**Comment by dnsmichi** [comment]
There's a public roadmap available on https://dev.icinga.org/projects/puppet-icinga2/roadmap ... I'd guess these issues should be resolved before tagging a final release (as Markus already told). Many of them still require patches and feedback from testers as far as I can see. Please comment on the issues themselves then.

**Pull request closed without merging**
