### PR TITLE
add CentOS5 support

### PR DESCRIPTION
**Pull request by dmizelle**
CentOS 5 is still receiving maintenance updates until 2017, so we should provide support for this case statement using operatingsystemmajrelease.

All the packages in the list are available within EPEL.

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi @dmizelle,

Would you be able to update the README's [Setup](https://github.com/Icinga/puppet-icinga2#setup) section and mention that the NRPE part of the module can be used on EL5?

Would you also be able to update the `metadata.json` file?

**Comment by dmizelle** [comment]
Thanks for the feedback @nickchappell. Hopefully the edits are what you are looking for. Let me know if any additional changes are needed.

**Comment by nickchappell** [comment]
Hi @dmizelle,

Do the server components work on CentOS 5 (don't have a CentOS 5 system handy to test with)?

**Comment by dmizelle** [comment]
Hey @nickchappell . Currently fighting this bug:
https://dev.icinga.org/issues/6807
with shroud in IRC right now. We're trying to see if we can fix it. Server packages won't install until it is resolved.

**Comment by dmizelle** [comment]
@gunnarbeutner just fixed the CentOS 5 repos, so cracking along more on this. Will update this PR when I'm done testing.

**Comment by dmizelle** [comment]
Greetings @nickchappell 

Did some further testing yesterday. Was able to install icinga2 successfully against a postgresql DB on CentOS 5.11 using my changes. Only stipulation is that the user needs PGSQL >9.0, and I have reflected that in the README.

Let me know if there's anything else.

**Comment by nickchappell** [comment]
Just for reference, I created a [dev.icinga.org](https://dev.icinga.org) issue: [#7674](https://dev.icinga.org/issues/7674)

**Comment by nickchappell** [comment]
Merged. Thanks @dmizelle!

**Pull request closed without merging**
