### PR TITLE
Add inline checkplugin file distribution method

### PR DESCRIPTION
**Pull request by arioch**
With this patch we can specify the content of `${checkplugin_libdir}/${checkplugin_name}` inline.

E.g.:

```
::icinga2::checkplugin { 'check_diskstats':
  checkplugin_file_distribution_method => 'inline'
  checkplugin_source_inline            => 'command[check_disks]=/usr/lib64/nagios/plugins/check_disk -w 20 -c 10 -p /'
}
```

Or in my case using hiera-yaml:

```

---
icinga2::checkplugin:
  check_diskstats:
    checkplugin_file_distribution_method: 'inline'
    checkplugin_source_inline:            'command[check_disks]=/usr/lib64/nagios/plugins/check_disk -w 20 -c 10 -p /'
```

### CODE REVIEW

**Comment by nickchappell** [comment]
Hi @arioch,

Could you add a note to the README documenting this?

**Comment by arioch** [comment]
As requested.

**Comment by nickchappell** [comment]
I opened a [dev.icinga.org](https://dev.icinga.org/) issue for this: [#8239](https://dev.icinga.org/issues/8239)

**Comment by nickchappell** [comment]
I merged this into the develop branch. Thanks @arioch!

**Comment by arioch** [comment]
I already opened https://dev.icinga.org/issues/8217 when sending this PR.
But I can't seem to close it myself...

**Pull request closed without merging**
