### PR TITLE
Command_endpoint for service and spec

### PR DESCRIPTION
**Pull request by erikanderson**
Ref: https://github.com/Icinga/puppet-icinga2/pull/176

### CODE REVIEW

**Comment by arioch** [comment]
Your tests seem to fail... 
If you can fix those I'll be happy to merge.

**Comment by erikanderson** [comment]
Yeah, I saw that last night, will keep working on it

**Comment by erikanderson** [comment]
@arioch tests should be passing

**Comment by arioch** [comment]
Excellent! 👍 
Merged upstream.

**Pull request closed without merging**
