### PR TITLE
Remove NRPE from the icinga2 module

### PR DESCRIPTION
**Pull request by lazyfrosch**
fixes #10416

Can I get any thoughts for that?

### CODE REVIEW

**Comment by arioch** [comment]
Haven't tested myself but looks good to me!
Finally someone had the courage to remove the NRPE cruft. :+1: 

Are you going to split it to a separate module or just dropping it altogether?

**Comment by lazyfrosch** [comment]
@arioch I'd leave the NRPE module for the community, moving the manifests they already use couldn't be that hard.

I've no current use in my environments.

**Comment by arioch** [comment]
:+1:

**Comment by lazyfrosch** [comment]
Let's do it

**Pull request merged**
