### PR TITLE
Fix inheritance of config owner/group/mode for the configuration files

### PR DESCRIPTION
**Pull request by TheFlyingCorpse**
Made it easier to inherit config owner/group/mode to configuration files from the globally set parameters.

### CODE REVIEW

**Comment by zachfi** [comment]
+1 though I don't see the modification to init.pp.

**Comment by TheFlyingCorpse** [comment]
@xaque208 - I did the modification that was already started in a few files under "manifests/object/", now its consistent in that it will inherit what is used. I dont change init because it sets the parameters based on what flavour the OS is. The intent with this change is to make it similar for all the created files that it inherits from the root class unless otherwise specified.

**Comment by TheFlyingCorpse** [comment]
Still waiting for this to be merged.

**Comment by arioch** [comment]
Excellent. 👍 
Merged upstream.

**Pull request closed without merging**
