### PR TITLE
FR: Generic apply_service object

### PR DESCRIPTION
**Pull request by jkroepke**
Hi,

currently it is impossible to create Service Object apply for like the [documentation](http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics?highlight-search=apply%20Service%20for#using-apply-for-custom-attribute-override) describe it.

I change the static apply_service_to_host manifest to a more generic apply_service manifest. You can do somethink like this right now:

```
icinga2::object::apply_service{ "if-":
  display_name => '"IF-" + interface_name',
  apply => 'for (interface_name => interface_config in host.vars.interfaces)';
}
```

I dont know, If a backward compatibility for object_apply_service_to_host. is required.

Regards,
Jam

### CODE REVIEW

**Comment by lazyfrosch** [comment]
Yeah, thats much better, thanks, will merge it later.

**Comment by arioch** [comment]
Could you also adjust readme.md to reflect these changes?

**Comment by jkroepke** [comment]
Yes.

**Comment by arioch** [comment]
Thanks!
Merged upstream.

**Comment by jkroepke** [comment]
I got some problems with the variables: I can not pass host variables to service variables, because icinga always quotes the strings at the config file.
As workaround, i'm using a new options vars_raw to buld config like http://docs.icinga.org/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#using-apply-object-attributes with this puppet module.

Anyone have a better solution?

**Pull request closed without merging**
